import Head from 'next/head';
import Dashboard from './blogs/Dashboard';
export default function Home() {
  return (
    <>
      <Head>
        <title> Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Dashboard></Dashboard>
    </>
  )
}
